global:
  scrape_interval: 1s

scrape_configs:
  # Job 1: Your actual Application data
  - job_name: 'app-metrics'
    static_configs:
      - targets: ['otel-collector:8889']

  # Job 2: The Collector's own performance data
  - job_name: 'otel-health'
    static_configs:
      - targets: ['otel-collector:8888']