name: Native AOT Build for All Services

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-readinglist:
    name: Build ReadingListService
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
    - name: Install MSVC Build Tools
      run: choco install visualstudio2022buildtools --package-parameters "--add Microsoft.VisualStudio.Workload.VCTools --includeRecommended --passive --locale en-US"
    - name: Publish Native AOT
      run: dotnet publish ReadingListService/ReadingListService.csproj -c Release -r win-x64
    - name: Upload Executable
      uses: actions/upload-artifact@v4
      with:
        name: ReadingListServiceExe
        path: ReadingListService/bin/Release/net9.0/win-x64/publish/ReadingListService.exe

  build-valuation:
    name: Build ValuationService
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
    - name: Install MSVC Build Tools
      run: choco install visualstudio2022buildtools --package-parameters "--add Microsoft.VisualStudio.Workload.VCTools --includeRecommended --passive --locale en-US"
    - name: Publish Native AOT
      run: dotnet publish ValuationService/ValuationService.csproj -c Release -r win-x64
    - name: Upload Executable
      uses: actions/upload-artifact@v4
      with:
        name: ValuationServiceExe
        path: ValuationService/bin/Release/net9.0/win-x64/publish/ValuationService.exe

  build-ingestion:
    name: Build IngestionService
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
    - name: Install MSVC Build Tools
      run: choco install visualstudio2022buildtools --package-parameters "--add Microsoft.VisualStudio.Workload.VCTools --includeRecommended --passive --locale en-US"
    - name: Publish Native AOT
      run: dotnet publish IngestionService/IngestionService.csproj -c Release -r win-x64
    - name: Upload Executable
      uses: actions/upload-artifact@v4
      with:
        name: IngestionServiceExe
        path: IngestionService/bin/Release/net9.0/win-x64/publish/IngestionService.exe

  build-persistence:
    name: Build PersistenceService
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
    - name: Install MSVC Build Tools
      run: choco install visualstudio2022buildtools --package-parameters "--add Microsoft.VisualStudio.Workload.VCTools --includeRecommended --passive --locale en-US"
    - name: Publish Native AOT
      run: dotnet publish PersistenceService/PersistenceService.csproj -c Release -r win-x64
    - name: Upload Executable
      uses: actions/upload-artifact@v4
      with:
        name: PersistenceServiceExe
        path: PersistenceService/bin/Release/net9.0/win-x64/publish/PersistenceService.exe
